### PR TITLE
Add netty native transport support

### PR DESCRIPTION
**Pull request by andy-yx-chen**
Add netty native transport support and test cases to cover PreferNativeTransport scenario

### CODE REVIEW

**Comment by vietj** [comment]
I think we need to add test for native transport for Travis CI, you can look at how it is achieved here https://github.com/eclipse-vertx/vert.x/blob/master/.travis.yml . You can test this in your own fork of this repo if you want.

**Comment by andy-yx-chen** [comment]
> I think we need to add test for native transport for Travis CI, you can look at how it is achieved here https://github.com/eclipse-vertx/vert.x/blob/master/.travis.yml . You can test this in your own fork of this repo if you want.

It looks like it's not just as easy as updating the Travis CI script, we need to update maven script as well in this project, will try

**Comment by andy-yx-chen** [comment]
@vietj , done with setting up another profile to test with nativeTransport, which has better coverage, thanks for the suggestion.

**Comment by codepitbull** [comment]
Ran the tests (using the Travid commandline) locally on my Ubuntu-box and things look good.
LGTM and I will merge it.

**Pull request merged**
