### PR TITLE
Implement new columns() API

### PR DESCRIPTION
**Pull request by pmlopes**
Depends on https://github.com/vert-x3/vertx-sql-common/pull/40

### CODE REVIEW

**Comment by tsegismont** [comment]
No tests here?

**Comment by pmlopes** [comment]
@tsegismont i don't think it will add anything since the columns variable is already used all over and is the base location for the resultset object to create the metadata.

**Comment by tsegismont** [comment]
Looking at the code, it seems there are good chances for `columns` to be
null (if you don't use `column("BLAH")`. Or am I missing something?

2017-03-30 14:17 GMT+02:00 Paulo Lopes <notifications@github.com>:

**Comment by Narigo** [comment]
As you are making `columns` available, I would add a test as well. Just to be safe that a refactoring that doesn't rely on `columns` as much won't lead to a regression.

Another question is if the user can mutate the returned `columns` list and may this cause trouble?

**Comment by tsegismont** [comment]
LGTM

**Pull request merged**
