### PR TITLE
Backported `Catch the exception thrown by the synchronization` to 3.6

### LINKED ISSUE #151: Exception was discarded, but it shouldn't
when I invoke from client but not connection, it's will get connection and do action in the callback. if the action throw a exception, and no exception handler of Context was setting .The exception will discard.

also see https://github.com/vert-x3/vertx-mysql-postgresql-client/issues/116

https://github.com/vert-x3/vertx-mysql-postgresql-client/blob/12a6e6f89478998a6075b34b7b0e8272dc2e6a14/vertx-mysql-postgresql-client-jasync/src/main/java/io/vertx/ext/asyncsql/impl/pool/AsyncConnectionPool.java#L115-L129

```kotlin
client.queryWithParams("select * from player where id=?",JsonArray().add(1).add(2)) {
    // callback never execute
}
```

```kotlin
client.getConnection() {
    try {
        it.queryWithParams("select * from player where id=?",JsonArray().add(1).add(2)) {
            // do something
        }
    } catch(e : Throwable) {
        //got the exception
    }
}
```

### PR DESCRIPTION
**Pull request by okou19900722**
fixed #151

### CODE REVIEW

**Comment by codepitbull** [comment]
Can you provide a test for the situation you are trying to solve with this change?

**Comment by okou19900722** [comment]
```java
  @Test
  public void test(TestContext context){
    JsonArray arr = new JsonArray().add(1).add(2);
    Async async = context.async();
    client.queryWithParams("?", arr, r -> {
      context.assertTrue(r.failed());
      context.assertTrue(r.cause() instanceof InsufficientParametersException);
      async.complete();
    });
  }
```
https://github.com/jasync-sql/jasync-sql/blob/8e168f442b3175c102bdbeb8e6e706f24962fe8a/mysql-async/src/main/java/com/github/jasync/sql/db/mysql/MySQLConnection.kt#L288-L301

**Comment by okou19900722** [comment]
Callback will never be called before modification

**Comment by codepitbull** [comment]
I will review everything this weekend to make sure this doesn't introduce breaking changes for current users.
Thanks for your effort :)

**Comment by okou19900722** [comment]
Hi @codepitbull , have you reviewed yet? It's a terrible problem. can you merge #156  before 3.7.1 release?

**Comment by codepitbull** [comment]
Yes, I already merged the other one. Merging this now.
Sorry for the delay.

**Pull request merged**
