### PR TITLE
Catch the exception thrown by the synchronization

### PR DESCRIPTION
**Pull request by okou19900722**

### CODE REVIEW

**Comment by vietj** [comment]
can you review this @codepitbull ?

**Comment by okou19900722** [comment]
We can switch the default branch to 3.8

**Comment by codepitbull** [comment]
Sorry, just now got time to take a closer look.
PR looks good and I couldn't find a way that would cause problems with the current implementattion.

**Comment by okou19900722** [comment]
The callback in the unit test will never be executed until the modification

**Pull request merged**
