### PR TITLE
Add SSL support (rebase + tests)

### PR DESCRIPTION
**Pull request by Narigo**
Rebased #78 and added tests.

### CODE REVIEW

**Comment by Narigo** [comment]
Please review @Mart-Bogdan @pmlopes - thanks a lot @Mart-Bogdan for the initial PR and sorry that it took so long...

**Comment by Mart-Bogdan** [comment]
@Narigo I've added new test case, for sslMode=prefer, and filed PR #90

**Comment by vietj** [comment]
@Narigo what is missing for merging this PR ?

**Comment by Mart-Bogdan** [comment]
@vietj @Narigo
I've added tests in #90

**Comment by vietj** [comment]
awesome guys thanks!

**Pull request merged**
